/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedCollabRouteImport } from './routes/_authenticated/collab'
import { Route as AuthenticatedCreateRouteImport } from './routes/_authenticated/create'
import { Route as AuthenticatedCreditsRouteImport } from './routes/_authenticated/credits'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as AuthenticatedEditorProjectIdRouteImport } from './routes/_authenticated/editor.$projectId'
import { Route as AuthenticatedLibraryProjectIdRouteImport } from './routes/_authenticated/library.$projectId'
import { Route as ApiPublicFapshiWebhookRouteImport } from './routes/api/public/fapshi-webhook'
import { Route as ApiPublicSunoCallbackRouteImport } from './routes/api/public/suno-callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCollabRoute = AuthenticatedCollabRouteImport.update({
  id: '/collab',
  path: '/collab',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreateRoute = AuthenticatedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreditsRoute = AuthenticatedCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEditorProjectIdRoute =
  AuthenticatedEditorProjectIdRouteImport.update({
    id: '/editor/$projectId',
    path: '/editor/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLibraryProjectIdRoute =
  AuthenticatedLibraryProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedLibraryRoute,
  } as any)
const ApiPublicFapshiWebhookRoute = ApiPublicFapshiWebhookRouteImport.update({
  id: '/api/public/fapshi-webhook',
  path: '/api/public/fapshi-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSunoCallbackRoute = ApiPublicSunoCallbackRouteImport.update({
  id: '/api/public/suno-callback',
  path: '/api/public/suno-callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/feed': typeof FeedRoute
  '/legal': typeof LegalRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/collab': typeof AuthenticatedCollabRoute
  '/create': typeof AuthenticatedCreateRoute
  '/credits': typeof AuthenticatedCreditsRoute
  '/library': typeof AuthenticatedLibraryRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/editor/$projectId': typeof AuthenticatedEditorProjectIdRoute
  '/library/$projectId': typeof AuthenticatedLibraryProjectIdRoute
  '/api/public/fapshi-webhook': typeof ApiPublicFapshiWebhookRoute
  '/api/public/suno-callback': typeof ApiPublicSunoCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/feed': typeof FeedRoute
  '/legal': typeof LegalRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/collab': typeof AuthenticatedCollabRoute
  '/create': typeof AuthenticatedCreateRoute
  '/credits': typeof AuthenticatedCreditsRoute
  '/library': typeof AuthenticatedLibraryRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/editor/$projectId': typeof AuthenticatedEditorProjectIdRoute
  '/library/$projectId': typeof AuthenticatedLibraryProjectIdRoute
  '/api/public/fapshi-webhook': typeof ApiPublicFapshiWebhookRoute
  '/api/public/suno-callback': typeof ApiPublicSunoCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/feed': typeof FeedRoute
  '/legal': typeof LegalRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/_authenticated/collab': typeof AuthenticatedCollabRoute
  '/_authenticated/create': typeof AuthenticatedCreateRoute
  '/_authenticated/credits': typeof AuthenticatedCreditsRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/_authenticated/editor/$projectId': typeof AuthenticatedEditorProjectIdRoute
  '/_authenticated/library/$projectId': typeof AuthenticatedLibraryProjectIdRoute
  '/api/public/fapshi-webhook': typeof ApiPublicFapshiWebhookRoute
  '/api/public/suno-callback': typeof ApiPublicSunoCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/changelog'
    | '/contact'
    | '/cookies'
    | '/feed'
    | '/legal'
    | '/mentions-legales'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/templates'
    | '/terms'
    | '/collab'
    | '/create'
    | '/credits'
    | '/library'
    | '/settings'
    | '/studio'
    | '/editor/$projectId'
    | '/library/$projectId'
    | '/api/public/fapshi-webhook'
    | '/api/public/suno-callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/changelog'
    | '/contact'
    | '/cookies'
    | '/feed'
    | '/legal'
    | '/mentions-legales'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/templates'
    | '/terms'
    | '/collab'
    | '/create'
    | '/credits'
    | '/library'
    | '/settings'
    | '/studio'
    | '/editor/$projectId'
    | '/library/$projectId'
    | '/api/public/fapshi-webhook'
    | '/api/public/suno-callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/changelog'
    | '/contact'
    | '/cookies'
    | '/feed'
    | '/legal'
    | '/mentions-legales'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/templates'
    | '/terms'
    | '/_authenticated/collab'
    | '/_authenticated/create'
    | '/_authenticated/credits'
    | '/_authenticated/library'
    | '/_authenticated/settings'
    | '/_authenticated/studio'
    | '/_authenticated/editor/$projectId'
    | '/_authenticated/library/$projectId'
    | '/api/public/fapshi-webhook'
    | '/api/public/suno-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChangelogRoute: typeof ChangelogRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  FeedRoute: typeof FeedRoute
  LegalRoute: typeof LegalRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TemplatesRoute: typeof TemplatesRoute
  TermsRoute: typeof TermsRoute
  ApiPublicFapshiWebhookRoute: typeof ApiPublicFapshiWebhookRoute
  ApiPublicSunoCallbackRoute: typeof ApiPublicSunoCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/collab': {
      id: '/_authenticated/collab'
      path: '/collab'
      fullPath: '/collab'
      preLoaderRoute: typeof AuthenticatedCollabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create': {
      id: '/_authenticated/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/credits': {
      id: '/_authenticated/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof AuthenticatedCreditsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/editor/$projectId': {
      id: '/_authenticated/editor/$projectId'
      path: '/editor/$projectId'
      fullPath: '/editor/$projectId'
      preLoaderRoute: typeof AuthenticatedEditorProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library/$projectId': {
      id: '/_authenticated/library/$projectId'
      path: '/$projectId'
      fullPath: '/library/$projectId'
      preLoaderRoute: typeof AuthenticatedLibraryProjectIdRouteImport
      parentRoute: typeof AuthenticatedLibraryRoute
    }
    '/api/public/fapshi-webhook': {
      id: '/api/public/fapshi-webhook'
      path: '/api/public/fapshi-webhook'
      fullPath: '/api/public/fapshi-webhook'
      preLoaderRoute: typeof ApiPublicFapshiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/suno-callback': {
      id: '/api/public/suno-callback'
      path: '/api/public/suno-callback'
      fullPath: '/api/public/suno-callback'
      preLoaderRoute: typeof ApiPublicSunoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedLibraryRouteChildren {
  AuthenticatedLibraryProjectIdRoute: typeof AuthenticatedLibraryProjectIdRoute
}

const AuthenticatedLibraryRouteChildren: AuthenticatedLibraryRouteChildren = {
  AuthenticatedLibraryProjectIdRoute: AuthenticatedLibraryProjectIdRoute,
}

const AuthenticatedLibraryRouteWithChildren =
  AuthenticatedLibraryRoute._addFileChildren(AuthenticatedLibraryRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCollabRoute: typeof AuthenticatedCollabRoute
  AuthenticatedCreateRoute: typeof AuthenticatedCreateRoute
  AuthenticatedCreditsRoute: typeof AuthenticatedCreditsRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
  AuthenticatedEditorProjectIdRoute: typeof AuthenticatedEditorProjectIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCollabRoute: AuthenticatedCollabRoute,
  AuthenticatedCreateRoute: AuthenticatedCreateRoute,
  AuthenticatedCreditsRoute: AuthenticatedCreditsRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
  AuthenticatedEditorProjectIdRoute: AuthenticatedEditorProjectIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ChangelogRoute: ChangelogRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  FeedRoute: FeedRoute,
  LegalRoute: LegalRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TemplatesRoute: TemplatesRoute,
  TermsRoute: TermsRoute,
  ApiPublicFapshiWebhookRoute: ApiPublicFapshiWebhookRoute,
  ApiPublicSunoCallbackRoute: ApiPublicSunoCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
